### PR TITLE
KT-40592 Inspection "Replace with loop over elements" replaces code incorrectly with nested loop over multidimensional array

### PR DESCRIPTION
**Pull request by t-kameyama**
Issue link: <https://youtrack.jetbrains.com/issue/KT-40592>

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
False-positive case:
https://youtrack.jetbrains.com/issue/KT-40592#focus=Comments-27-4394086.0-0 

```
fun foo() {
    val a = listOf(1, 2, 3)
    val b = listOf(11, 22, 33, 44, 55)
    for (i in 0 until a.size) {
        println(b[i])  //note `b` collection is used
    }
}
```

**Comment by vladimirdolzhenko** [comment]
Looks like it is worth to check that `i` is used in the context of the same array as in `until` statement 

Through the code from snippet  https://youtrack.jetbrains.com/issue/KT-40592#focus=Comments-27-4394086.0-0 should highlight potential problem of out-of-bound-exception https://youtrack.jetbrains.com/issue/KTIJ-870

**Comment by t-kameyama** [comment]
> False-positive case:
> https://youtrack.jetbrains.com/issue/KT-40592#focus=Comments-27-4394086.0-0
> 
> ```
> fun foo() {
>     val a = listOf(1, 2, 3)
>     val b = listOf(11, 22, 33, 44, 55)
>     for (i in 0 until a.size) {
>         println(b[i])  //note `b` collection is used
>     }
> }
> ```

See:
https://github.com/JetBrains/intellij-kotlin/blob/8f3c3abc852bad0bfe7996f1d96aad894648fb84/idea/testData/inspectionsLocal/replaceManualRangeWithIndicesCalls/usedForOtherArray.kt

https://github.com/JetBrains/intellij-kotlin/blob/8f3c3abc852bad0bfe7996f1d96aad894648fb84/idea/testData/inspectionsLocal/replaceManualRangeWithIndicesCalls/usedForOtherArray.kt.after


スクリーンショット 2021-01-06 21 12 20

**Comment by vladimirdolzhenko** [comment]
Indeed, you're right

LGTM

**Pull request closed without merging**
