### PR TITLE
KT-30037 Intention to remove braces from "if" for all branches

### PR DESCRIPTION
**Pull request by t-kameyama**
Issue link: <https://youtrack.jetbrains.com/issue/KT-30037>

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
I think it would be nice to add option to add/remove braces at `then` position i.e.

```
    if (true) <caret> { // To have here ' Remove braces from all `if` statements' right after `Remove braces from `if` statement`
        0
    } else {
        1
    }
```
image

WDYT ?

**Comment by t-kameyama** [comment]
> I think it would be nice to add option to add/remove braces at `then` position i.e.

Fixed in c723fc5c5f049a3d16e7d2c3cb01109e7d933528

**Comment by vladimirdolzhenko** [comment]
based on https://github.com/JetBrains/intellij-kotlin/blob/master/idea/testData/quickfix/typeMismatch/variableInitializedWithNull2.kt#L10

```
fun foo(condition: Boolean) {
    val x = null
    if (condition) {
        x = "abc"<caret>
    }
}
```

I don't think it is worth to add option 'Add/Remove braces from all if statements' iff there is only one (_then_) statement

**Comment by t-kameyama** [comment]
> I don't think it is worth to add option 'Add/Remove braces from all if statements' iff there is only one (_then_) statement

Fixed in aed7c6c

**Comment by vladimirdolzhenko** [comment]
LGTM.

Manually adjusted two test data files (with missed `Add braces to all 'if' statements`) and merged as https://github.com/JetBrains/intellij-kotlin/commit/d3292d7e23fe0d528ee996faa069a084813d4b22

Thank you

**Pull request closed without merging**
