### PR TITLE
FIR UAST: test updates after member reordering from FIR LC

### PR DESCRIPTION
**Pull request by jsjeon**
To be updated: first 7 commits are identical to #93

------

The changes in this PR are purely test data updates in FIR UAST. There are a few cases where rendered outputs are almost identical yet the order is the only difference. It turns out that the order of member functions of class generated by FIR LC is different from that of FE 1.0 LC. [KOTLIN-CR-152](https://kotlin.jetbrains.space/p/kotlin/reviews/152/) fixed those in FIR LC.

### CODE REVIEW

**Comment by darthorimar** [comment]
This PR brokes some tests, could you please fix them?

```
FirHighlightingMetaInfoTestGenerated.testNamedArguments 
FirHighlightingMetaInfoTestGenerated.testInvokeCall 
FirHighlightingMetaInfoTestGenerated.testKotlinInjection 
HighLevelQuickFixTestGenerated$AddExclExclCall$TypeMismatch.testQualifiedArgument 
FirLegacyUastIdentifiersTestGenerated.testPropertyWithAnnotation 
FirLegacyUastIdentifiersTestGenerated.testDestructuringDeclaration 
FirLegacyUastIdentifiersTestGenerated.testParameterPropertyWithAnnotation 
FirLegacyUastIdentifiersTestGenerated.testSimpleAnnotated 
FirLegacyUastIdentifiersTestGenerated.testLambdaReturn 
FirLegacyUastIdentifiersTestGenerated.testWhenAndDestructing 
```

**Review by darthorimar — CHANGES_REQUESTED** [review]
This PR brokes some tests, could you please fix them?

```
FirHighlightingMetaInfoTestGenerated.testNamedArguments 
FirHighlightingMetaInfoTestGenerated.testInvokeCall 
FirHighlightingMetaInfoTestGenerated.testKotlinInjection 
HighLevelQuickFixTestGenerated$AddExclExclCall$TypeMismatch.testQualifiedArgument 
FirLegacyUastIdentifiersTestGenerated.testPropertyWithAnnotation 
FirLegacyUastIdentifiersTestGenerated.testDestructuringDeclaration 
FirLegacyUastIdentifiersTestGenerated.testParameterPropertyWithAnnotation 
FirLegacyUastIdentifiersTestGenerated.testSimpleAnnotated 
FirLegacyUastIdentifiersTestGenerated.testLambdaReturn 
FirLegacyUastIdentifiersTestGenerated.testWhenAndDestructing 
```

**Comment by darthorimar** [comment]
Then will be fixed, I will merge this PR together with https://github.com/JetBrains/intellij-kotlin/pull/92 and https://github.com/JetBrains/intellij-kotlin/pull/93

**Comment by jsjeon** [comment]
I've rebased branches one by one; ran tests per (connected) branch; and found that:

1) kt-211-master is broken, and will be fixed with #97.

2) `FirHighlightingMetaInfoTestGenerated.*` were broken at `uast-commonize-convert-parent`. Actually, I didn't expect UAST usage like that! Newly added, last 3 commits in #92 will fix those.

3) All tests under `HighLevelQuickFixTestGenerated$AddExclExclCall$TypeMismatch` are passing locally. Could you double-check they're tested with `prr/jsjeon/uast-member-order` in `kotlin` repo?

4) Same for all `FirLegacyUastIdentifiersTestGenerated`. They're part of `uast-kotlin-fir` that I always run and run, so should catch them. :) I.e., not failing on my side. If you're still seeing failures, let me know how failures look like (via slack).

**Comment by darthorimar** [comment]
Merged into https://github.com/JetBrains/intellij-community/tree/kt-212-master

**Pull request closed without merging**
