### PR TITLE
KT-43126 "Redundant 'inner' modifier" inspection should warn when access containing class members of not this object

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-43126
https://youtrack.jetbrains.com/issue/KT-43122

### CODE REVIEW

**Review by yanex — COMMENTED** [review]
Failing case:

```
class Foo {
    fun Foo.foo() {}

    inner class Bar {
        fun bar(f: Foo) {
            f.foo()
        }
    }
}
```

**Comment by yanex** [comment]
A bit more complicated scenario still fails:

```
class Foo {
    fun Foo.foo() {}

    inner class Bar {
        fun bar(f: Foo) {
            with (f) {
                f.foo()
            }
        }
    }
}
```

**Comment by t-kameyama** [comment]
Fixed in 9e91483, PTAL.

**Comment by t-kameyama** [comment]
https://github.com/JetBrains/intellij-community/pull/1610

**Pull request closed without merging**
