### PR TITLE
KT-42857 False-positive "Throwable instance '...' is not thrown" in Kotlin with Optional<T>.orElseThrow()

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-42857

### CODE REVIEW

**Review by dimonchik0036 — CHANGES_REQUESTED** [review]
A similar case:
```kotlin
fun test() {
    val d = dods {
        RuntimeException() // FP warning
    }
}

fun dods(err: () -> RuntimeException): RuntimeException {
    return err().also { println(it) }
}
```

**Comment by t-kameyama** [comment]
> A similar case:
> 
> ```kotlin
> fun test() {
>     val d = dods {
>         RuntimeException() // FP warning
>     }
> }
> 
> fun dods(err: () -> RuntimeException): RuntimeException {
>     return err().also { println(it) }
> }
> ```

Fixed in c121cd3

**Review by dimonchik0036 — APPROVED** [review]
Thanks!

**Comment by dimonchik0036** [comment]
Fixed in https://github.com/JetBrains/intellij-kotlin/commit/80a3f4901a303bd56472c470a881bbcbbff92d0a

**Pull request closed without merging**
