### PR TITLE
KT-39266 EXPERIMENTAL_API_USAGE_ERROR: "Add @OptIn" quickfix should have higher sort order priority

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-39266

スクリーンショット 2020-11-13 16 45 46

### CODE REVIEW

**Comment by klunnii** [comment]
1. Solution unfortunatly doesn't work for me. When I try to insert suggested fix nothing happens from the user prospective. Meanwhile the following assertion is triggered:
```
2020-11-13 13:29:02,459 [ 865911]  ERROR - pplication.impl.LaterInvocator - Incorrect priority of QuickFixWithDelegateFactory wrapper for org.jetbrains.kotlin.idea.quickfix.AddAnnotationFix 
java.lang.AssertionError: Incorrect priority of QuickFixWithDelegateFactory wrapper for org.jetbrains.kotlin.idea.quickfix.AddAnnotationFix
	at org.jetbrains.kotlin.idea.quickfix.QuickFixWithDelegateFactory.invoke(QuickFixWithDelegateFactory.kt:48)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:208)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:249)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:249)
```
2. Would it be possible to add test(s)?

**Comment by t-kameyama** [comment]
> 1. Solution unfortunatly doesn't work for me. When I try to insert suggested fix nothing happens from the user prospective. Meanwhile the following assertion is triggered:

Fixed in 6a4dee0.

> 2. Would it be possible to add test(s)?

Added in 73a083b.

**Comment by klunnii** [comment]
Thank you! Merged - https://github.com/JetBrains/intellij-kotlin/commit/8bdc0fdff5aba5e2d87eb2e20b407a89275b649e.

**Comment by klunnii** [comment]
I'm sorry, the author of the commit was somehow lost. I'll try to figure out what happend not to allow this happen again.

**Comment by klunnii** [comment]
This one should be fine now: https://github.com/JetBrains/intellij-kotlin/commit/a21abdedacee83a706bc8565fbf3bf998303af18.

**Pull request closed without merging**
